<?php

/** Implementation of hook_field_info */
function tms_field_field_info(){
	return array(
		'taxonomy_term_bundle_reference' => array(
			'label' => t('Term bundle reference'),
			'description' => t('This field stores a reference to a taxonomy term of a defined taxonomy bundle.'),
			'default_widget' => 'taxonomy_bundle_term_list_widget',
			'default_formatter' => 'taxonomy_term_reference_link',
			'settings' => array(
				'parent' => '0',
				'bundle' => '',
			),
		),
	);
}

/** Implementation of hook_field_settings_form */
function tms_field_field_settings_form($field, $instance, $has_data){
	module_load_include('inc', 'taxonomy_menu_sync');
	module_load_include('inc', 'tms_field');

	// Get proper values for 'allowed_values_function', which is a core setting.
	$vocabularies = taxonomy_get_vocabularies();
	$options = array();
	foreach($vocabularies as $vocabulary){
		$options[$vocabulary->machine_name] = $vocabulary->name;
	}

	$form['parent'] = array(
		'#type' => 'value',
		'#value' => $field['settings']['parent'],
	);
	$bundles = tms_field_get_bundle_options();
	$form['bundle'] = array(
		'#type' => 'select',
		'#title' => t('Taxonomy bundle'),
		'#default_value' => $field['settings']['bundle'],
		'#options' => $bundles,
		'#required' => false,
		'#empty_option' => '',
		'#description' => t('The taxonomy bundle for this field.'),
		'#disabled' => $has_data,
	);

	return $form;
}

/** Implementation of hook_field_is_empty */
function tms_field_field_is_empty($item, $field){
	return empty($item);
}

/** Implementation of hook_field_widget_info */
function tms_field_field_widget_info(){
	return array(
		'taxonomy_bundle_term_list_widget' => array(
			'label' => t('Taxonomy bundle list'),
			'description' => t('Complete list of available taxonomy terms'),
			'field types' => array('taxonomy_term_bundle_reference'),
			'settings' => array(),
			'behaviors' => array(
				'multiple values' => FIELD_BEHAVIOR_CUSTOM,
			),
		),
	);
}

/** Implementation of hook_field_widget_form */
function tms_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element){
	$element['#attached']['css'][] = drupal_get_path('module', 'tms_field').'/'.'tms_field.css';

	$defaults = array();
	foreach($items as $value){
		$tid = $value['tid'];
		$defaults[$tid] = $tid;
	}

	switch($instance['widget']['type']){
		case 'taxonomy_bundle_term_list_widget':
			module_load_include('inc', 'taxonomy_menu_sync');

			$indent = '<div class="tree-indent">-</div>';

			list($vocabulary_machine_name, $bundle_machine_name) = explode('|', $field['settings']['bundle']);

			if($vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_machine_name)){
				$list = taxonomy_menu_sync_get_terms_list($vocabulary);
				$options = array();

				if($field['cardinality'] == 1){
					$default_value = $defaults ? reset($defaults) : null;

					if(!$instance['required']){
						$options[0] = t('None');
						$default_value = $default_value ? $default_value : 0;
					}
				}else{
					$default_value = $defaults;
				}

				foreach($list as $term){
					$indentation = '';
					for($i = 0; $i < $term->depth; $i++){
						$indentation .= $indent;
					}

					$options[$term->tid] = $term->name;
				}
				$element += array(
					'#type' => $field['cardinality'] == 1 ? 'radios' : 'checkboxes',
					'#options' => $options,
					'#default_value' => $default_value,
					'#taxonomy_bundle' => $bundle_machine_name,
					'#taxonomy_vocabulary' => $vocabulary,
				);
				foreach($list as $term){
					$indentation = '';
					for($i = 0; $i < $term->depth; $i++){
						$indentation .= $indent;
					}
					$element += array(
						$term->tid => array(
							'#prefix' => '<div class="indented-option">'.$indentation,
							'#suffix' => '</div>',
							'#disabled' => $bundle_machine_name && $term->bundle['machine_name'] != $bundle_machine_name,
						)
					);
				}
			}
			break;
	}

	$element += array(
		'#element_validate' => array('tms_field_field_widget_validate'),
	);

	return $element;
}

function tms_field_field_widget_validate($element, &$form_state){
	module_load_include('inc', 'taxonomy_menu_sync');

	$values = array_filter(array_values((array) $element['#value']));
	if($element['#required'] && empty($values)){
		form_error($element, t('!name field is required.', array('!name' => $element['#title'])));
	}

	$valid_values = array();
	foreach($values as $value){
		$term = taxonomy_term_load($value);
		$term_bundle = taxonomy_menu_sync_get_term_bundle($term);
		if(!$term_bundle || $term_bundle['machine_name'] != $element['#taxonomy_bundle'] || $term->vid != $element['#taxonomy_vocabulary']->vid){
			form_error($element, $element['#title'].': '.t('An illegal choice has been detected.'));
		}else{
			$valid_values[] = $value;
		}
	}

	form_set_value($element, $valid_values, $form_state);
}

/** Implementation of hook_node_insert */
function tms_field_node_insert($node){
	// Add taxonomy index entries for the node.
	tms_field_build_node_index($node);
}

/** Implementation of hook_node_update */
function tms_field_node_update($node){
	// Always rebuild the node's taxonomy index entries on node save.
	taxonomy_delete_node_index($node);
	tms_field_build_node_index($node);
}

/** Implementation of hook_node_delete */
function tms_field_node_delete($node){
	// Clean up the {taxonomy_index} table when nodes are deleted.
	taxonomy_delete_node_index($node);
}

/** Builds and inserts taxonomy index entries for a given node */
function tms_field_build_node_index($node){
	// We maintain a denormalized table of term/node relationships, containing
	// only data for current, published nodes.
	$status = NULL;
	if(variable_get('taxonomy_maintain_index_table', TRUE)){
		// If a node property is not set in the node object when node_save() is
		// called, the old value from $node->original is used.
		if(!empty($node->original)){
			$status = (int)(!empty($node->status) || (!isset($node->status) && !empty($node->original->status)));
			$sticky = (int)(!empty($node->sticky) || (!isset($node->sticky) && !empty($node->original->sticky)));
		}else{
			$status = (int)(!empty($node->status));
			$sticky = (int)(!empty($node->sticky));
		}
	}
	// We only maintain the taxonomy index for published nodes.
	if($status){
		// Collect a unique list of all the term IDs from all node fields.
		$tid_all = array();
		foreach(field_info_instances('node', $node->type) as $instance){
			$field_name = $instance['field_name'];
			$field = field_info_field($field_name);
			if($field['module'] == 'tms_field' && $field['storage']['type'] == 'field_sql_storage'){
				// If a field value is not set in the node object when node_save() is
				// called, the old value from $node->original is used.
				if(isset($node->{$field_name})){
					$items = $node->{$field_name};
				}elseif(isset($node->original->{$field_name})){
					$items = $node->original->{$field_name};
				}else{
					continue;
				}
				foreach(field_available_languages('node', $field) as $langcode){
					if(!empty($items[$langcode])){
						foreach($items[$langcode] as $item){
							$tid_all[$item['tid']] = $item['tid'];
						}
					}
				}
			}
		}
		// Insert index entries for all the node's terms.
		if(!empty($tid_all)){
			$query = db_insert('taxonomy_index')->fields(array('nid', 'tid', 'sticky', 'created'));
			foreach($tid_all as $tid){
				$query->values(array(
					'nid' => $node->nid,
					'tid' => $tid,
					'sticky' => $sticky,
					'created' => $node->created,
				));
			}
			$query->execute();
		}
	}
}
